### ISSUE TITLE
Crear tablazas de números

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-ASOCO#1]

**Comment by mgarenas** [comment]
Pablo, es mejor que vayas asignando las cosas a cada uno, así no nos dormimos en los laureles.

**Comment by fergunet** [comment]
Tranqui @mgarenas, que este iba asignado para mí, ahora os toca a vosotros en un rato ;)

**Comment by vrivas** [comment]
Me pillais en Huelva, chicos.
Si alguien quiere asignarme algo, volveré el día 4 a Granada.
Cheers
