### ISSUE TITLE
Contestar a un revisor

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-ASOCO#13]
Un revisor dice textualmente:

_4. "State of the art" which is the title of Section 2 is inappropriate._

¿Por qué? ¿Lo cambio a Background?

**Comment by unintendedbear** [comment]
¿Cómo? Background o Related Work está bien, sí, pero no sé por qué está mal
State of the Art.

**Comment by JJ** [comment]
A ver si es realmente "state of the art". Es decir, un estado cuantitativo
de qué es lo que hay hecho, no una referencia deslavazada a varios
artículos relacionados.
