### ISSUE TITLE
Sinónimo para "Adaptation of parameters to hardware"

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-ASOCO#15]
Un revisor dice que "adaptation" sólo debería usarse cuando los parámetros cambian en tiempo real (como en AdSi). Sin embargo en el texto tengo cosas como "adaptation of fixed sizes to computational resources" (entre otras) para indicar que adaptamos los parámetros fijos a la potencia de las máquinas. ¿Qué palabra se os ocurre para diferenciar "adaptation (online)" de "adaptation to hardware" ?

**Comment by JJ** [comment]
"fitting" "matching"

El 6 de marzo de 2015, 17:53, Pablo García Sánchez <notifications@github.com

> escribió:
> 
> Un revisor dice que "adaptation" sólo debería usarse cuando los parámetros
> cambian en tiempo real (como en AdSi). Sin embargo en el texto tengo cosas
> como "adaptation of fixed sizes to computational resources" (entre otras)
> para indicar que adaptamos los parámetros fijos a la potencia de las
> máquinas. ¿Qué palabra se os ocurre para diferenciar "adaptation (online)"
> de "adaptation to hardware" ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-ASOCO/issues/15.

## 

JJ

**Comment by amorag** [comment]
Yo propongo ‘Adjustment’ para el ajuste de parámetros a las posibilidades del hardware, previo a la ejecución. ;)

De: Pablo García Sánchez [mailto:notifications@github.com] 
Enviado el: viernes, 6 de marzo de 2015 17:53
Para: geneura-papers/2015-ASOCO
Asunto: [2015-ASOCO] Sinónimo para "Adaptation of parameters to hardware" (#15)

Un revisor dice que "adaptation" sólo debería usarse cuando los parámetros cambian en tiempo real (como en AdSi). Sin embargo en el texto tengo cosas como "adaptation of fixed sizes to computational resources" (entre otras) para indicar que adaptamos los parámetros fijos a la potencia de las máquinas. ¿Qué palabra se os ocurre para diferenciar "adaptation (online)" de "adaptation to hardware" ?

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2015-ASOCO/issues/15 .  https://github.com/notifications/beacon/AC6-WoCJnwnu23RsAfXKVEyihTIlUh4xks5nydMGgaJpZM4DqwN-.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5645 / Base de datos de virus: 4299/9236 - Fecha de publicación: 03/06/15

---

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5645 / Base de datos de virus: 4299/9185 - Fecha de publicación: 02/26/15
Base de datos de virus interno no está actualizado.
