### ISSUE TITLE
Discusión sobre los resultados

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015-ASOCO#17]
Habría que analizar mejor las tablas 6 y 7 y realmente _explicar_ los resultados. No se trata de poner 1000 tablas y gráficos, si no los explicamos correctamente. Primero: ¿es mejor el tamaño heterogéneo? Para ver si lo es o no, tenemos que compararlo con el hardware homogéneo. Si el resultado el el hardware homogéneo es mejor para tamño heterogéneo (lo es en el caso de OneMax), ¿a qué se debe? ¿Qué principio exploración/explotación entra en juego?

Es **fundamental** que entendamos correctamente los resultados y sepamos explicarlos. Todos los gráficos deben ir encaminados a la explicación de estos resultados y en las conclusiones debe estar bien claro.

**Comment by fergunet** [comment]
He comentado más los resultados y enlazándolo con las preguntas de la introducción (también he cambiado las conclusiones), pero me gustaría vuestra ayuda para dejarlo más fino. Echadle un vistazo si podéis, que mañana sigo.
