### ISSUE TITLE
Propuesta de nuevo título

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-ASOCO#18]
Un revisor me dijo que _Population size adaptation in distributed evolutionary algorithms on heterogeneous clusters_ no era del todo correcto, así que lo cambié a _Effect of population size in distributed evolutionary algorithms on heterogeneous clusters_. @JJ propone que ponga _studying_, así que lo he dejado como _Studying the effect of population size in distributed evolutionary algorithms on heterogeneous clusters_

¿Os parece bien? ¿Alguna otra sugerencia? Había pensado algo en plan _Fitting the population size in distributed evolutionary algorithms on heterogeneous clusters_ para dejar claro lo de "fitting".

**Comment by pacastillo** [comment]
Yo veo mejor el del "studying"

**Comment by amorag** [comment]
¿Y la mezcla de todo?

"Studying the population size fitting effect in distributed..."

:D

**Comment by gstvrmrlpz** [comment]
el artículo no sólo es un estudio del efecto del tamaño de la 
población... así que no lo tengo muy claro

**Comment by fergunet** [comment]
Ya, pienso lo mismo.
