### ISSUE TITLE
Justificar por qué hemos elegido 1024 individuos como población

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-ASOCO#4]
En principio hemos elegido 1024 individuos porque es más fácil de dividir entre 4 y 8 nodos, dándole 256/128 a cada nodo, que es un número suficientemente grande para optimizar a la máquina (por ejemplo, a la más lente en algunas configuraciones se queda con 4 u 8), pero haría falta justificarlo bien. ¿Alguna referencia? 

Algún revisor pide que se haga con más tamaños de población, pero claro, eso implica multiplicar las 18 configuraciones distintas otra vez. 

Creo que con poner referencia al trabajo de Alba y Nebro que también usan tamaños de población fijos estaría bien.

**Comment by pacastillo** [comment]
En el paper:
(1) F.Luna, C. Estébanez, C. León, J.M. Chaves-González, A. J. Nebro, R. Aler, C. Segura, M.A. Vega-Rodríguez, E.Alba, J.M. Valls, G. Miranda, J.A. Gómez-Pulido, Optimization Algorithms for Large-Scale Real-World Instances of the Frequency Assignment Problem, Soft Computing, 15(5):975-990, 2011
Simplemente indican que se llevaron a cabo una serie de experimentos previos para establecer los valores de los parámetros de ejecución. Después pasan a listar los parámetros con los valores elegidos.

Luego, en el paper:
(2) J. J. Durillo, A. J. Nebro, F. Luna, C. A. Coello, E. Alba, Convergence Speed in Multi-Objective Metaheuristics: Efficiency Criteria and Empirical Study, International Journal for Numerical Methods in Engineering, Wiley, 84(11):1344- 1375, 2010

directamente indican:
4.2. Parameters settings
As commented in the introduction, we chose a set of parameters settings that have been used in the previous studies (see the references in Table I), without spending any effort in trying to find the best possible configurations. All the GAs (NSGA-II, SPEA2, and MOCell) and GDE3 use an internal population of size equal to 100; the size of the archive is also 100 in PAES, SMPSO, GDE3, MOCell, and AbYSS. SMPSO has been configured with 100 particles. For AbYSS, the population and the reference set have a size of 20 solutions.

En este otro paper:
(3) E. Alba, F. Chicano, Observations in using Parallel and Sequential Evolutionary Algorithms for Automatic Software Testing, Computers and Operations Research, 35(10):3161-3183, 2008

explican la experimentación del siguiente modo:
we compare the distributed ES (dES) against the panmictic one (panES) and the distributed GA (dGA) against the panmictic genetic algorithm (panGA). With this comparison we want to study the influence of the decentralized design in the search.
For this reason we set the population size and the maximum number of evaluations in all the algorithms to the same values. The parameters of the algorithms are presented in Tables 3 and 4. In all the algorithms we use 25 individuals in the population, random selection and the stop criterion consists of finding a solution or reaching a maximum of 500 evaluations (in the distributed algorithms each of the five islands performs a maximum of 100 evaluations).

Por último, en:
(4) E. Alba, G. Luque, C. A. Coello, E. Hernández, A Comparative Study of Serial and Parallel Heuristics used to Design Combinational Logic Circuits, Optimization, Methods, and Software, 22(3):485-509, June 2007

dicen:
As our main goal was to analyze the behavior of different heuristics and the impact of parallelism, no particular effort was placed in fine-tuning the parameters for each of the circuits tried. The population sizes,mutation,and crossover rates used correspond to the values previously reported for a traditional (binary) GA [9]. In all the evolutionary algorithms, the population is composed of 320 individuals

Como ves, no se justifica el número de individuos elegido para formar la población.
Como mucho dicen que lo hacen tras hacer una experimentación previa.
No hay una razón concreta en estos artículos para establecer un valor u otro. Sí se paran en los valores elegidos para los diferentes operadores utilizados.

Sí que encuentro interesante el párrafo que he extraido del paper (3).

**Comment by JJ** [comment]
También los artículos de Juanlu
http://link.springer.com/article/10.1007/s10710-009-9096-z#page-1 en los
que citamos los artículos de Lobo  cia.
