### ISSUE TITLE
Ver si hay diferencia significativa entre el número de evaluaciones para cada método

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-ASOCO#7]
En la carpeta boxplot/data de este repo están los ficheros para generar los boxplots. Necesito saber si hay diferencias significativas en el número de evaluaciones.

Los archivos a usar son EVALS_(NODOS)_(PROBLEMA)_(INSTANCIA) Por cada fichero necesito saber si hay diferencias significativas:
- Entre la columna 1 y la 2
- Entre la columna 1 y la 3
- Entre la columna 4 y la 5

No hace falta que me des los p-values, ni kolmogorov ni nada, algo como
EVALS_4X_MMDP_150.csv Si No Si
EVALS_4X_MMDP_200.csv Si Si No
...
me vale

**Comment by pacastillo** [comment]
Los nombres de las columnas (para referenciarlos luego en los resultados).
    mismotam1 diftam2 tamadap3
    mismotamHet4 diftamHet5

Como te comentaba en un email previo, hay que mirar la primera y tercera comparación, y luego la última, para cada archivo (mira el archivo 1 "EVALS_4X_MMDP_150" para ver la explicación).

1----- EVALS_4X_MMDP_150

Comparisons
                 obs.dif critical.dif difference
diftam-mismotam    21.25     18.62079       TRUE     (comparación entre columnas 2 con 1)
diftam-tamadap     27.65     18.62079       TRUE
mismotam-tamadap    6.40     18.62079      FALSE     (comparación entre columnas 1 con 3)

Comparisons
                        obs.dif critical.dif difference
diftamHet5-mismotamHet4   13.25     10.18427       TRUE     (comparación entre columnas 4 con 5)

2----- EVALS_4X_MMDP_240
Comparisons
                 obs.dif critical.dif difference
diftam-mismotam   26.675     18.62079       TRUE
diftam-tamadap    33.775     18.62079       TRUE
mismotam-tamadap   7.100     18.62079      FALSE

Comparisons
                         obs.dif critical.dif difference
diftamHet5-mismotamHet4 11.34079     10.06106       TRUE

3----- EVALS_4X_MMDP_300
Comparisons
                 obs.dif critical.dif difference
diftam-mismotam   14.850     18.62079      FALSE
diftam-tamadap    24.525     18.62079       TRUE
mismotam-tamadap   9.675     18.62079      FALSE

Comparisons
                        obs.dif critical.dif difference
diftamHet5-mismotamHet4     0.9     10.18427      FALSE

4----- EVALS_4X_ONEMAX_5000
Comparisons
                 obs.dif critical.dif difference
diftam-mismotam   55.725     18.62079       TRUE
diftam-tamadap     8.550     18.62079      FALSE
mismotam-tamadap  64.275     18.62079       TRUE

Comparisons
                        obs.dif critical.dif difference
diftamHet5-mismotamHet4      40     10.18427       TRUE

5----- EVALS_4X_ONEMAX_10000
Comparisons
                 obs.dif critical.dif difference
diftam-mismotam       40     18.62079       TRUE
diftam-tamadap        80     18.62079       TRUE
mismotam-tamadap      40     18.62079       TRUE

Comparisons
                        obs.dif critical.dif difference
diftamHet5-mismotamHet4    37.5     9.886931       TRUE

6----- EVALS_4X_ONEMAX_15000
Comparisons
                 obs.dif critical.dif difference
diftam-mismotam       40     18.62079       TRUE
diftam-tamadap        80     18.62079       TRUE
mismotam-tamadap      40     18.62079       TRUE

Comparisons
                        obs.dif critical.dif difference
diftamHet5-mismotamHet4      40     10.18427       TRUE

7----- EVALS_4X_ROSENBROCK_10
Comparisons
                 obs.dif critical.dif difference
diftam-mismotam   30.275     18.62079       TRUE
diftam-tamadap    18.275     18.62079      FALSE
mismotam-tamadap  48.550     18.62079       TRUE

Comparisons
                        obs.dif critical.dif difference
diftamHet5-mismotamHet4    29.3     10.18427       TRUE

8----- EVALS_4X_ROSENBROCK_30
Comparisons
                 obs.dif critical.dif difference
diftam2-mismotam1    4.125     18.62079      FALSE
diftam2-tamadap3    21.900     18.62079       TRUE
mismotam1-tamadap3  17.775     18.62079      FALSE

Comparisons
                        obs.dif critical.dif difference
diftamHet5-mismotamHet4    15.2     10.18427       TRUE

9----- EVALS_4X_ROSENBROCK_50
Comparisons
                 obs.dif critical.dif difference
diftam-mismotam    2.975     18.62079      FALSE
diftam-tamadap    16.600     18.62079      FALSE
mismotam-tamadap  13.625     18.62079      FALSE

Comparisons
                        obs.dif critical.dif difference
diftamHet5-mismotamHet4     5.3     10.18427      FALSE

10----- EVALS_8X_MMDP_150
Comparisons
                 obs.dif critical.dif difference
diftam-mismotam   25.975     18.62079       TRUE
diftam-tamadap     8.150     18.62079      FALSE
mismotam-tamadap  17.825     18.62079      FALSE

Comparisons
                        obs.dif critical.dif difference
diftamHet5-mismotamHet4     7.2     10.18427      FALSE

11----- EVALS_8X_MMDP_240
Comparisons
                 obs.dif critical.dif difference
diftam-mismotam    2.850     18.62079      FALSE
diftam-tamadap    16.725     18.62079      FALSE
mismotam-tamadap  19.575     18.62079       TRUE

Comparisons
                        obs.dif critical.dif difference
diftamHet5-mismotamHet4    0.15     10.18427      FALSE

12----- EVALS_8X_MMDP_300
Comparisons
                 obs.dif critical.dif difference
diftam-mismotam    0.875     18.62079      FALSE
diftam-tamadap    14.750     18.62079      FALSE
mismotam-tamadap  15.625     18.62079      FALSE

Comparisons
                        obs.dif critical.dif difference
diftamHet5-mismotamHet4       0     10.12202      FALSE

13----- EVALS_8X_ONEMAX_5000
Comparisons
                 obs.dif critical.dif difference
diftam-mismotam    40.35     18.62079       TRUE
diftam-tamadap     79.65     18.62079       TRUE
mismotam-tamadap   39.30     18.62079       TRUE

Comparisons
                        obs.dif critical.dif difference
diftamHet5-mismotamHet4      40     10.18427       TRUE

14----- EVALS_8X_ONEMAX_10000
Comparisons
                 obs.dif critical.dif difference
diftam-mismotam     53.1     18.62079       TRUE
diftam-tamadap      66.9     18.62079       TRUE
mismotam-tamadap    13.8     18.62079      FALSE

Comparisons
                        obs.dif critical.dif difference
diftamHet5-mismotamHet4      40     10.18427       TRUE

15----- EVALS_8X_ONEMAX_15000
Comparisons
                 obs.dif critical.dif difference
diftam-mismotam   76.875     18.62079       TRUE
diftam-tamadap    42.450     18.62079       TRUE
mismotam-tamadap  34.425     18.62079       TRUE

Comparisons
                        obs.dif critical.dif difference
diftamHet5-mismotamHet4      40     10.18427       TRUE

16----- EVALS_8X_ROSENBROCK_10
Comparisons
                 obs.dif critical.dif difference
diftam-mismotam   15.075     18.62079      FALSE
diftam-tamadap    39.675     18.62079       TRUE
mismotam-tamadap  54.750     18.62079       TRUE

Comparisons
                        obs.dif critical.dif difference
diftamHet5-mismotamHet4     4.3     10.18427      FALSE

17----- EVALS_8X_ROSENBROCK_30
Comparisons
                 obs.dif critical.dif difference
diftam-mismotam   37.750     18.62079       TRUE
diftam-tamadap     2.275     18.62079      FALSE
mismotam-tamadap  40.025     18.62079       TRUE

Comparisons
                        obs.dif critical.dif difference
diftamHet5-mismotamHet4    1.05     10.18427      FALSE

18----- EVALS_8X_ROSENBROCK_50
Comparisons
                 obs.dif critical.dif difference
diftam-mismotam   11.875     18.62079      FALSE
diftam-tamadap     2.300     18.62079      FALSE
mismotam-tamadap   9.575     18.62079      FALSE

Comparisons
                         obs.dif critical.dif difference
diftamHet5-mismotamHet4 1.744737     10.06106      FALSE
